name: CI Comprehensive

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # 1) build-and-test job
  build-and-test-the-thing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

  # 2) Call local workflow directly (no steps block)
  invoke-local-child:
    uses: ./.github/workflows/child-workflow.yml
    with:
      message: "Direct workflow call from main workflow"
  
  # 3) Job with dependency
  job-with-dependency:
    needs: build-and-test-the-thing
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job that depends on another job"
  
  # 4) Call nested workflow (workflow that calls another workflow)
  call-nested-workflow:
    uses: ./.github/workflows/nested-workflow.yml
  
  # 5) Job that uses local composite action
  use-local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use local action
        uses: ./.github/actions/local-echo
        with:
          message: "Using a local composite action"
        id: local-action
      - run: echo "Local action timestamp: ${{ steps.local-action.outputs.timestamp }}"
  
  # 6) Job with output parameters
  output-job:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-output.outputs.value }}
    steps:
      - id: set-output
        run: echo "value=some-value" >> $GITHUB_OUTPUT
  
  # 7) Job that uses outputs from another job
  use-output-job:
    needs: output-job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Using output from previous job: ${{ needs.output-job.outputs.result }}"
  
  # 8) Job that calls reusable workflow and captures its output
  call-with-output:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      message: "Calling workflow and capturing its output"
  
  # 9) Job that uses output from a called workflow
  use-workflow-output:
    needs: call-with-output
    runs-on: ubuntu-latest
    steps:
      - run: echo "Status from called workflow: ${{ needs.call-with-output.outputs.status }}"
  
  # 10) Job whose step dispatches another workflow via REST API
  trigger-another-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow via REST API
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: child-workflow.yml
          ref: main